"""Add missing columns to conversations

Revision ID: 8a9b82819e40
Revises: 1ab60e5da129
Create Date: 2026-02-21 04:19:29.509134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8a9b82819e40'
down_revision: Union[str, Sequence[str], None] = '1ab60e5da129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('freelancer_profiles')
    op.drop_table('clickup_mappings')
    op.drop_table('pricing_history')
    op.drop_table('_alembic_tmp_analytics_metrics')
    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('follow_up_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('follow_up_at',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.drop_column('notes')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('analytics_metrics', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_analytics_metrics',
    sa.Column('time_frame', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category_or_niche', sa.VARCHAR(length=255), nullable=True),
    sa.Column('total_proposals_sent', sa.INTEGER(), nullable=False),
    sa.Column('total_jobs_won', sa.INTEGER(), nullable=False),
    sa.Column('win_rate_percentage', sa.FLOAT(), nullable=False),
    sa.Column('total_revenue', sa.FLOAT(), nullable=False),
    sa.Column('total_connects_spent', sa.INTEGER(), nullable=False),
    sa.Column('revenue_per_connect', sa.FLOAT(), nullable=False),
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_history',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('job_category', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_description_snippet', sa.TEXT(), nullable=True),
    sa.Column('keywords', sqlite.JSON(), nullable=True),
    sa.Column('amount_charged', sa.FLOAT(), nullable=False),
    sa.Column('budget_type', sa.VARCHAR(length=10), server_default=sa.text("'fixed'"), nullable=True),
    sa.Column('competing_bids_count', sa.FLOAT(), nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=20), server_default=sa.text("'unknown'"), nullable=True),
    sa.Column('client_location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('proposal_link', sa.VARCHAR(length=500), nullable=True),
    sa.Column('room_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clickup_mappings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('job_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('clickup_task_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('clickup_list_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_sync_hash', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freelancer_profiles',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=True),
    sa.Column('overview', sa.TEXT(), nullable=True),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('hourly_rate', sa.FLOAT(), nullable=True),
    sa.Column('niches', sqlite.JSON(), nullable=True),
    sa.Column('style_guide', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('room_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['conversations.room_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
