"""Add sync metadata to Conversation

Revision ID: d6568eedfd3d
Revises: 687ed812a058
Create Date: 2026-02-20 17:41:11.288753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6568eedfd3d'
down_revision: Union[str, Sequence[str], None] = '687ed812a058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_message_timestamp', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_message_preview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=50), nullable=False, server_default='not_synced'))
        batch_op.add_column(sa.Column('message_count_synced', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('message_count_synced')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('last_message_preview')
        batch_op.drop_column('last_message_timestamp')
        batch_op.drop_column('last_message_id')
